// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Ktk2J6M8jug8Mj6ZeomGImVL_18lE3g',
    appId: '1:866826225471:web:1d1c635a80bd1d9379b58a',
    messagingSenderId: '866826225471',
    projectId: 'realtime-database-flutte-b4854',
    authDomain: 'realtime-database-flutte-b4854.firebaseapp.com',
    databaseURL: 'https://realtime-database-flutte-b4854-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-database-flutte-b4854.appspot.com',
    measurementId: 'G-VKSWM7QTDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBft731Y3R9PORWWnVNE_5I-41Nta6wPJA',
    appId: '1:866826225471:android:84c7b673e24efb2e79b58a',
    messagingSenderId: '866826225471',
    projectId: 'realtime-database-flutte-b4854',
    databaseURL: 'https://realtime-database-flutte-b4854-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-database-flutte-b4854.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx6mXx2hJe1trQaY9UzEhWZDD4zQt3Mds',
    appId: '1:866826225471:ios:3dee5a1e00a723e179b58a',
    messagingSenderId: '866826225471',
    projectId: 'realtime-database-flutte-b4854',
    databaseURL: 'https://realtime-database-flutte-b4854-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-database-flutte-b4854.appspot.com',
    androidClientId: '866826225471-4j5jeithjhasr0113qv3i3vt9sis3p02.apps.googleusercontent.com',
    iosClientId: '866826225471-l7k2bbogi75d1s6l1i6lgqdd8k892aea.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Ktk2J6M8jug8Mj6ZeomGImVL_18lE3g',
    appId: '1:866826225471:web:a2cd405cea989e6779b58a',
    messagingSenderId: '866826225471',
    projectId: 'realtime-database-flutte-b4854',
    authDomain: 'realtime-database-flutte-b4854.firebaseapp.com',
    databaseURL: 'https://realtime-database-flutte-b4854-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-database-flutte-b4854.appspot.com',
    measurementId: 'G-GEM95VVN2S',
  );
}
